name: intentional failed workflow
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: try to fail
        run: exit 1